-- ============================================================
-- PRY2204 - SEMANA 7 - ACTIVIDAD FORMATIVA
-- Holding Carpenter SPA
-- Alumno: Alejandro Serrano
-- Fecha: 28/09/2026
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = PRY2204_S7;

-- ============================================================
-- CASO 1: CREACIÓN DE TABLAS
-- ============================================================

-- REGION
CREATE TABLE region (
    id_region      NUMBER(2) GENERATED BY DEFAULT AS IDENTITY 
                   (START WITH 7 INCREMENT BY 2) NOT NULL,
    nombre_region  VARCHAR2(50) NOT NULL,
    CONSTRAINT region_pk PRIMARY KEY (id_region)
);

-- GENERO
CREATE TABLE genero (
    id_genero      NUMBER(2) NOT NULL,
    descripcion    VARCHAR2(20) NOT NULL,
    CONSTRAINT genero_pk PRIMARY KEY (id_genero)
);

-- ESTADO_CIVIL
CREATE TABLE estado_civil (
    id_estado_civil   NUMBER(2) NOT NULL,
    descripcion_est   VARCHAR2(20) NOT NULL,
    CONSTRAINT estado_civil_pk PRIMARY KEY (id_estado_civil)
);

-- TITULO
CREATE TABLE titulo (
    id_titulo          VARCHAR2(3) NOT NULL,
    descripcion_titulo VARCHAR2(60) NOT NULL,
    CONSTRAINT titulo_pk PRIMARY KEY (id_titulo)
);

-- IDIOMA
CREATE TABLE idioma (
    id_idioma     NUMBER(3) GENERATED BY DEFAULT AS IDENTITY 
                  (START WITH 25 INCREMENT BY 3) NOT NULL,
    nombre_idioma VARCHAR2(30) NOT NULL,
    CONSTRAINT idioma_pk PRIMARY KEY (id_idioma)
);

-- COMUNA
CREATE TABLE comuna (
    id_comuna     NUMBER(5) NOT NULL,
    nombre_comuna VARCHAR2(50) NOT NULL,
    cod_region    NUMBER(2) NOT NULL,
    CONSTRAINT comuna_pk PRIMARY KEY (id_comuna),
    CONSTRAINT comuna_region_fk FOREIGN KEY (cod_region) REFERENCES region(id_region)
);

-- COMPANIA
CREATE TABLE compania (
    id_empresa       NUMBER(2) NOT NULL,
    nombre_empresa   VARCHAR2(50) NOT NULL,
    calle            VARCHAR2(50),
    numeracion       VARCHAR2(10),
    renta_promedio   NUMBER(10),
    pct_aumento      NUMBER(4,3),
    cod_comuna       NUMBER(5) NOT NULL,
    CONSTRAINT compania_pk PRIMARY KEY (id_empresa),
    CONSTRAINT compania_comuna_fk FOREIGN KEY (cod_comuna) REFERENCES comuna(id_comuna)
);

-- PERSONAL
CREATE TABLE personal (
    rut_persona       NUMBER(8) NOT NULL,
    dv_persona        CHAR(1) NOT NULL,
    primer_nombre     VARCHAR2(25) NOT NULL,
    segundo_nombre    VARCHAR2(25),
    primer_apellido   VARCHAR2(25) NOT NULL,
    segundo_apellido  VARCHAR2(25),
    fecha_nacimiento  DATE NOT NULL,
    email             VARCHAR2(100),
    direccion         VARCHAR2(50),
    sueldo            NUMBER(10) NOT NULL,
    cod_comuna        NUMBER(5) NOT NULL,
    cod_genero        NUMBER(2) NOT NULL,
    cod_estado_civil  NUMBER(2) NOT NULL,
    cod_empresa       NUMBER(2) NOT NULL,
    CONSTRAINT personal_pk PRIMARY KEY (rut_persona),
    CONSTRAINT personal_compania_fk FOREIGN KEY (cod_empresa) REFERENCES compania(id_empresa),
    CONSTRAINT personal_comuna_fk FOREIGN KEY (cod_comuna) REFERENCES comuna(id_comuna),
    CONSTRAINT personal_estado_civil_fk FOREIGN KEY (cod_estado_civil) REFERENCES estado_civil(id_estado_civil),
    CONSTRAINT personal_genero_fk FOREIGN KEY (cod_genero) REFERENCES genero(id_genero)
);

-- TITULACION
CREATE TABLE titulacion (
    cod_titulo       VARCHAR2(3) NOT NULL,
    rut_persona      NUMBER(8) NOT NULL,
    fecha_titulacion DATE NOT NULL,
    CONSTRAINT titulacion_pk PRIMARY KEY (cod_titulo, rut_persona),
    CONSTRAINT titulacion_titulo_fk FOREIGN KEY (cod_titulo) REFERENCES titulo(id_titulo),
    CONSTRAINT titulacion_personal_fk FOREIGN KEY (rut_persona) REFERENCES personal(rut_persona)
);

-- DOMINIO
CREATE TABLE dominio (
    id_idioma    NUMBER(3) NOT NULL,
    rut_persona  NUMBER(8) NOT NULL,
    nivel        VARCHAR2(25) NOT NULL,
    CONSTRAINT dominio_pk PRIMARY KEY (id_idioma, rut_persona),
    CONSTRAINT dominio_idioma_fk FOREIGN KEY (id_idioma) REFERENCES idioma(id_idioma),
    CONSTRAINT dominio_personal_fk FOREIGN KEY (rut_persona) REFERENCES personal(rut_persona)
);

-- ============================================================
-- CASO 2: ALTER TABLE (Reglas de negocio)
-- ============================================================

ALTER TABLE personal ADD CONSTRAINT personal_email_un UNIQUE (email);

ALTER TABLE personal ADD CONSTRAINT personal_dv_ck 
CHECK (dv_persona IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE personal ADD CONSTRAINT personal_sueldo_ck 
CHECK (sueldo >= 450000);

-- ============================================================
-- CASO 3: POBLAMIENTO
-- ============================================================

-- POBLAR IDIOMA
INSERT INTO idioma (nombre_idioma) VALUES ('Inglés');
INSERT INTO idioma (nombre_idioma) VALUES ('Chino');
INSERT INTO idioma (nombre_idioma) VALUES ('Alemán');
INSERT INTO idioma (nombre_idioma) VALUES ('Español');
INSERT INTO idioma (nombre_idioma) VALUES ('Francés');

-- POBLAR REGION
INSERT INTO region (nombre_region) VALUES ('Arica y Parinacota');
INSERT INTO region (nombre_region) VALUES ('Metropolitana');
INSERT INTO region (nombre_region) VALUES ('La Araucania');

-- SEQUENCE COMUNA
CREATE SEQUENCE seq_comuna START WITH 1101 INCREMENT BY 6 NOCACHE;

-- POBLAR COMUNA
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'Amapolas', 7);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'Los Alamos', 9);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'Las Camelias', 11);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'FLORES S.A.', 11);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'AVDA VIC. MACKENA', 9);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'PEDRO LATORRE', 11);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'LATINA D.32', 9);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'D. ALAMEDA', 11);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'SUCRE', 9);
INSERT INTO comuna VALUES (seq_comuna.NEXTVAL, 'SUECIA', 9);

-- SEQUENCE COMPANIA
CREATE SEQUENCE seq_compania START WITH 10 INCREMENT BY 5 NOCACHE;

-- POBLAR COMPANIA
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'CCyRojas', 'Amapolas', '506', 1857000, 0.5, 1101);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'SenTTy', 'Los Alamos', '3490', 897000, 0.025, 1107);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'Praxia LTDA', 'Las Camelias', '11098', 2157000, 0.035, 1113);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'TIC spa', 'FLORES S.A.', '4357', 857000, NULL, 1119);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'SANTANA LTDA', 'AVDA VIC. MACKENA', '106', 757000, 0.015, 1125);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'FLORES Y ASOCIADOS', 'PEDRO LATORRE', '557', 589000, 0.015, 1131);
INSERT INTO compania VALUES (seq_compania.NEXTVAL, 'J.A. HOFFMAN', 'LATINA D.32', '509', 1857000, 0.025, 1137);

COMMIT;

-- ============================================================
-- CASO 4: INFORMES
-- ============================================================

-- INFORME 1: Simulación de Renta Promedio
SELECT 
    nombre_empresa                              AS "Nombre Empresa",
    calle || ' ' || numeracion                  AS "Dirección",
    renta_promedio                              AS "Renta Promedio",
    ROUND(renta_promedio * (1 + NVL(pct_aumento,0))) AS "Simulación de Renta"
FROM compania
ORDER BY "Renta Promedio" DESC, "Nombre Empresa" ASC;

-- INFORME 2: Nueva simulación +15%
SELECT 
    id_empresa                                              AS "CODIGO EMPRESA",
    nombre_empresa                                          AS "EMPRESA",
    renta_promedio                                          AS "PROM RENTA ACTUAL",
    ROUND(NVL(pct_aumento,0) + 0.15, 3)                     AS "PCT AUMENTADO EN 15%",
    ROUND(renta_promedio * (1 + NVL(pct_aumento,0) + 0.15)) AS "RENTA AUMENTADA"
FROM compania
ORDER BY "PROM RENTA ACTUAL" ASC, "EMPRESA" DESC;